spring:
  profiles:
    active: dev
  application:
    name: business-rule-engine
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog-master.yml
    enabled: true

logging:
  level:
    root: INFO
  file:
    name: logs/app.log
