spring:
  application:
    name: business-rule-engine
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/business_rule_engine
    username: changeit
    password: changeit
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog-master.yml
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.gs1eg.business_rule_engine: DEBUG
  file:
    name: logs/app.log
